// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChFTIHP8xfBEPY0z1HqWT9FOl7236TPo8',
    appId: '1:634431870480:web:d4c1f61e451dc0801c1c95',
    messagingSenderId: '634431870480',
    projectId: 'rit-club',
    authDomain: 'rit-club.firebaseapp.com',
    databaseURL: 'https://rit-club-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rit-club.firebasestorage.app',
    measurementId: 'G-KY4R7NVX88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtL1qkwhGge0f-vPhSMGf9SWOXU1tfdKc',
    appId: '1:634431870480:android:95b20a63af11e8e51c1c95',
    messagingSenderId: '634431870480',
    projectId: 'rit-club',
    databaseURL: 'https://rit-club-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rit-club.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH0FMThDpptlXJ4NChW2qvYdx8NK_lAw0',
    appId: '1:634431870480:ios:315736a15a9e2e451c1c95',
    messagingSenderId: '634431870480',
    projectId: 'rit-club',
    databaseURL: 'https://rit-club-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rit-club.firebasestorage.app',
    iosBundleId: 'com.example.ritClub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH0FMThDpptlXJ4NChW2qvYdx8NK_lAw0',
    appId: '1:634431870480:ios:315736a15a9e2e451c1c95',
    messagingSenderId: '634431870480',
    projectId: 'rit-club',
    databaseURL: 'https://rit-club-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rit-club.firebasestorage.app',
    iosBundleId: 'com.example.ritClub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChFTIHP8xfBEPY0z1HqWT9FOl7236TPo8',
    appId: '1:634431870480:web:f3a14a9273f67d771c1c95',
    messagingSenderId: '634431870480',
    projectId: 'rit-club',
    authDomain: 'rit-club.firebaseapp.com',
    databaseURL: 'https://rit-club-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rit-club.firebasestorage.app',
    measurementId: 'G-NBN3JLS05F',
  );
}
